@startuml
class PerceptronMultilayer {
    - Integer nbPrototype;
    - List<Vertex> input;
    - List<Vertex> hidden;
    - List<Vertex> output;

    - Graph<Float> g
    + computeStructure();
    + initializeWeight();
    - Float forwardPropagation(List<Float> input);
    - backPropagation(Float expected, Float actual);
}
class Structure{
    - Integer nbHiddenLayer
    - Integer nbInputLayer
    - Integer nbOutputLayer
}
class SigmoidFunction{
    float compute(float x);
    flot prime((float x);
}

@enduml